language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script: pytest --cov=smtp2go_django tests
after_success:
- coveralls
notifications:
  slack:
    secure: mCYWJk5BX2ZRuUK1AweUbVq2yjlTXQlVc7844zKaSN/sM8j7k/0561xfBTH5/JAPLKBkG72dt35eezf6+uiMKTe4tkNUeXowsjV4fEzbkqe4ZQRGL/GQHyvmz5Mr8SaZzrwKRj9O7t5q8HNR25ha+n0Cq2smjqI4Ssgt2/p5A+0utm3bnINdsYyVpZ/4UQO4E08R1ghEC5Wb8DdREb0L8aoMDt2V2NYoTKrPjaEm6LsciF8rFY9mMldGSnanor8AHlHaW2/E7XINXnTLOYfT7nKYWKS1uHlDc6rLj5bulvtJg6PrY0Pw3H/eHg9TkWR2U2GTbkCqhnP/+ghBQsIW+ZEzwut/EMCT4EMujdjVCz2vwZWgwYNWcbHXJIpw9TJML+UF54lo8XEqr996An/hAUnKbl4zVdqdxwLmQpj4MSyCDXnLZOqVO+7DjRiICHm5tp4C7t5nK8WLEgOv3WXTZ9A9xUzHSq0Rjudo8lV7Bi6sYOrPJIH8LKsh2H0HRCbN/8eJFrKWEw7HPhefCTYTcNDk6hz4CMbLYDIcffmHjghi7UDnwI2/2wxSBY2BWhn6tYbu0JzD/dWgaygzZr3w8zK1iMRgPhAyVTOwb4T7T4SnhjbyUEe6QpbTdmkRiUq53/qmhbGZaRiCh8Eeh/Z5UHdTpxzCSaQPT6yavA+ZeSg=
