language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script: pytest --cov=smtp2go_django tests
after_success:
- coveralls
notifications:
  slack:
    secure: CCHGFd4GIGGLBZ0YwbWhV+QDYXzgMz86sqYUxoJx7jSMoi6zW2gu/U8Kt40uxyM/XsSMwW+3qxdr1ZqpvShsZJWmngH/9il8dKReELSAHFOz2lT+m7Gn0ZvWfr+KmbyFGDBFBW5C/uAxWB2UW55vChbVQ7CyoTi3LCmmTJmh1DkARJsg43uQHgYlGnLWYy59Jc3AQ9kGtbOmqZs/InDusthTl+JoaE9zlf3PsfdKk9xiLc5SyfRkfulUQt9L1rQD4LQzN/ofgRyba8Im+mUhd75uZMBaqGg5yZHkcDWkZXqck22ogqGn3+2RVvjy1vKMEIESGlJnSoPPZU2wPGe1YxqQ+L/1EjUcEOz5cGAo5wgzGgV+xUqSjjRve/mGOEq9RDyRvXjAlt7sgHx/Mibw4ILt1E1+TlIrLA66mOixDZ7AKw1QAgI6j098NINykrhj1uwCDYedoLUuG3sfNc6IxdXdncEUSVJE/kwslgYC6wZIHo1mtbxRUFwEtz7HalbgwqE3XKD7XtvsmMKdpxtRumFQqM1VbVNk/K2VX1782K2RhJgtfLPJwMDW0kxzk9Ka+JH3MWvo22EtbJdwFD+Hmxf3m3D2PviSkI8gQn3LP7i4AOMRT5dHTfEjskDsxTyz8vHzeXUK+n8bTpyqx52Ez83sD6vyxihIY8HiERlJOVY=
